DROP TABLE IF EXISTS university.students_courses CASCADE;
DROP TABLE IF EXISTS university.teachers_courses CASCADE;
DROP TABLE IF EXISTS university.timetable;
DROP TABLE IF EXISTS university.teacher;
DROP TABLE IF EXISTS university.student;
DROP TABLE IF EXISTS university.staff;
DROP TABLE IF EXISTS university.groups;
DROP TABLE IF EXISTS university.departments;
DROP TABLE IF EXISTS university.faculties;
DROP TABLE IF EXISTS university.courses;
DROP TABLE IF EXISTS university.classroom;
DROP TABLE IF EXISTS university.admin;
