spring:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/university
      username: university_admin
      password: '1234'
      pool-size: 30
      
  jpa:
    hibernate:
      ddl-auto: validate
      
  flyway:
    table: schema_history
    schemas: university
        